[workspace]
resolver = '2'

members = [ "evolution_training", 
    "matrix",
    "neural_network",
    "quoridor", "render",
    "neural_network_logger",
    "neural_network_logger", "play_ai_game",
]
