[package]
name = "evolution_training"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
neural_network = {path = "../neural_network"}
matrix = {path = "../matrix"}
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
