[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
matrix = {path = "../matrix"}
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
